// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppScssModule {
  export interface IAppScss {
    app: string;
    "color-white": string;
    colorWhite: string;
    "font-weight-bold": string;
    "font-weight-light": string;
    "font-weight-regular": string;
    "font-weight-thin": string;
    fontWeightBold: string;
    fontWeightLight: string;
    fontWeightRegular: string;
    fontWeightThin: string;
    "title-font-weight-regular": string;
    titleFontWeightRegular: string;
  }
}

declare const AppScssModule: AppScssModule.IAppScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AppScssModule.IAppScss;
};

export = AppScssModule;
