// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LandingPageScssNamespace {
  export interface ILandingPageScss {
    chip: string
    "color-white": string
    colorWhite: string
    flexible: string
    "font-weight-bold": string
    "font-weight-light": string
    "font-weight-regular": string
    "font-weight-thin": string
    fontWeightBold: string
    fontWeightLight: string
    fontWeightRegular: string
    fontWeightThin: string
    "landing-page": string
    landingPage: string
    "title-font-weight-regular": string
    titleFontWeightRegular: string
  }
}

declare const LandingPageScssModule: LandingPageScssNamespace.ILandingPageScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LandingPageScssNamespace.ILandingPageScss
}

export = LandingPageScssModule
