// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LandingPageScssModule {
  export interface ILandingPageScss {
    breweries: string;
    "color-white": string;
    colorWhite: string;
    "fb-container-style": string;
    fbContainerStyle: string;
    "font-weight-bold": string;
    "font-weight-light": string;
    "font-weight-regular": string;
    "font-weight-thin": string;
    fontWeightBold: string;
    fontWeightLight: string;
    fontWeightRegular: string;
    fontWeightThin: string;
    "landing-page": string;
    landingPage: string;
    "title-font-weight-regular": string;
    titleFontWeightRegular: string;
  }
}

declare const LandingPageScssModule: LandingPageScssModule.ILandingPageScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LandingPageScssModule.ILandingPageScss;
};

export = LandingPageScssModule;
